name: Smart Contract Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  foundry-tests:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Foundry build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Foundry tests
        run: |
          forge test -vvv
        id: test

  hardhat-tests:
    name: Hardhat Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Hardhat tests
        run: npx hardhat test

      - name: Run coverage (optional)
        run: npx hardhat coverage
        continue-on-error: true

  all-tests:
    name: All Tests Passed
    runs-on: ubuntu-latest
    needs: [foundry-tests, hardhat-tests]
    steps:
      - name: Summary
        run: echo "All tests passed successfully!"
